server:
  address: localhost
  port: 8080

spring:
  datasource: #mysql 접속 설정
    url: jdbc:mysql://localhost:3306/study_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: joshua
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: #jpa 설정
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false #hibernate가 실행한 sql을 출력한다.
        format_sql: true #hibernate가 실행한 sql을 출력할 때 보기 쉽게 정렬한다.
        use_sql_comments: false #query 출력시 주석도 함께 출력한다.
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #DB 방언 설정

    # 각DB당 방언
    # H2      : org.hibernate.dialect.H2Dialect
    # Oracle  : org.hibernate.dialect.Oracle11gDialect
    # MySql   : org.hibernate.dialect.MySQL5InnoDBDialect



logging.level.org.hibernate: #sql 로그 출력관련
  SQL: TRACE
  type.descriptor.sql : TRACE

---
spring:
  profiles: local
server:
  port : 8080

---
spring:
  profiles : dev
server:
  port: 8081
